In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.utils import np_utils
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model
from PIL import Image, ImageOps
import numpy

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [4]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [5]:
y_train[2]

4

In [6]:
X_train = X_train.reshape(60000, 28, 28, 1).astype('float32')
X_test = X_test.reshape(10000, 28, 28, 1).astype('float32')

In [7]:
number_of_classes = 10
Y_train = np_utils.to_categorical(y_train, number_of_classes)
Y_test = np_utils.to_categorical(y_test, number_of_classes)

In [8]:
Y_train[2]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

In [9]:
model = Sequential()
model.add(Conv2D(64, (3, 3), input_shape=(28, 28, 1), activation="relu"))
model.add(Conv2D(32, (3, 3), activation="relu"))
model.add(Flatten())
model.add(Dense(number_of_classes, activation="softmax"))

In [10]:
model.compile(loss='categorical_crossentropy', optimizer="Adam", metrics=["accuracy"])

In [11]:
model.fit(X_train, Y_train, batch_size=32, epochs=5, validation_data=(X_test,Y_test))

Epoch 1/5
1875/1875 [==============================] - 202s 107ms/step - loss: 0.2101 - accuracy: 0.9544 - val_loss: 0.0874 - val_accuracy: 0.9754
Epoch 2/5
1875/1875 [==============================] - 198s 106ms/step - loss: 0.0730 - accuracy: 0.9779 - val_loss: 0.0839 - val_accuracy: 0.9751
Epoch 3/5
1875/1875 [==============================] - 197s 105ms/step - loss: 0.0505 - accuracy: 0.9844 - val_loss: 0.0816 - val_accuracy: 0.9763
Epoch 4/5
1875/1875 [==============================] - 198s 106ms/step - loss: 0.0395 - accuracy: 0.9872 - val_loss: 0.0924 - val_accuracy: 0.9774
Epoch 5/5
1875/1875 [==============================] - 196s 105ms/step - loss: 0.0293 - accuracy: 0.9908 - val_loss: 0.0955 - val_accuracy: 0.9773


In [12]:
metrics = model.evaluate(X_test, Y_test, verbose=0)
print("Metrics (Test Loss & Test Accuracy): ")
print(metrics)

Metrics (Test Loss & Test Accuracy): 
[0.09553150087594986, 0.9772999882698059]


In [13]:
prediction = model.predict(X_test[:4])
print(prediction)

1/1 [==============================] - 0s 120ms/step
[[5.30540012e-09 2.51312204e-19 1.81370075e-11 3.67861808e-09
  6.20272868e-15 1.04088535e-11 1.05602247e-20 1.00000000e+00
  8.70853736e-13 3.34059932e-11]
 [2.38511880e-12 9.16995473e-12 9.99999881e-01 3.05540020e-08
  1.91797101e-15 6.03836500e-16 7.06798602e-08 1.15181240e-18
  8.34660840e-10 3.25099970e-15]
 [9.93601816e-07 9.94327128e-01 7.02436373e-05 1.20594077e-08
  4.48158447e-04 1.38274606e-06 2.55904297e-07 1.28422871e-05
  5.13883540e-03 1.96131154e-07]
 [9.99999523e-01 4.70895092e-14 9.20402088e-11 6.59786014e-14
  1.39885813e-12 1.02227731e-12 4.18505664e-07 2.30705538e-10
  5.35530821e-12 1.59704374e-08]]


In [14]:
print(numpy.argmax(prediction, axis=1))
print(Y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
model.save("model.h5")