In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.utils import np_utils
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model
from PIL import Image, ImageOps
import numpy

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [4]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [6]:
y_train[2]

4

In [7]:
X_train = X_train.reshape(60000, 28, 28, 1).astype('float32')
X_test = X_test.reshape(10000, 28, 28, 1).astype('float32')

In [8]:
number_of_classes = 10
Y_train = np_utils.to_categorical(y_train, number_of_classes)
Y_test = np_utils.to_categorical(y_test, number_of_classes)

In [9]:
Y_train[2]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

In [10]:
model = Sequential()
model.add(Conv2D(64, (3, 3), input_shape=(28, 28, 1), activation="relu"))
model.add(Conv2D(32, (3, 3), activation="relu"))
model.add(Flatten())
model.add(Dense(number_of_classes, activation="softmax"))

In [11]:
model.compile(loss='categorical_crossentropy', optimizer="Adam", metrics=["accuracy"])

In [12]:
model.fit(X_train, Y_train, batch_size=32, epochs=5, validation_data=(X_test,Y_test))

Epoch 1/5
1875/1875 [==============================] - 218s 116ms/step - loss: 0.2664 - accuracy: 0.9488 - val_loss: 0.1134 - val_accuracy: 0.9677
Epoch 2/5
1875/1875 [==============================] - 227s 121ms/step - loss: 0.0715 - accuracy: 0.9786 - val_loss: 0.0680 - val_accuracy: 0.9801
Epoch 3/5
1875/1875 [==============================] - 223s 119ms/step - loss: 0.0497 - accuracy: 0.9848 - val_loss: 0.0737 - val_accuracy: 0.9789
Epoch 4/5
1875/1875 [==============================] - 228s 121ms/step - loss: 0.0356 - accuracy: 0.9884 - val_loss: 0.1018 - val_accuracy: 0.9759
Epoch 5/5
1875/1875 [==============================] - 223s 119ms/step - loss: 0.0289 - accuracy: 0.9910 - val_loss: 0.1189 - val_accuracy: 0.9727


In [13]:
metrics = model.evaluate(X_test, Y_test, verbose=0)
print("Metrics (Test Loss & Test Accuracy): ")
print(metrics)

Metrics (Test Loss & Test Accuracy): 
[0.11885372549295425, 0.9726999998092651]


In [14]:
prediction = model.predict(X_test[:4])
print(prediction)

1/1 [==============================] - 0s 117ms/step
[[1.5553506e-13 2.2531239e-21 6.0422885e-14 3.2380171e-11 3.4523727e-18
  8.0916343e-17 6.5804552e-26 1.0000000e+00 8.9661738e-14 9.1142914e-13]
 [3.4408809e-11 5.0599353e-14 1.0000000e+00 3.7543727e-16 2.0705436e-20
  4.4782644e-18 9.0154636e-13 1.3409557e-19 2.0104537e-15 6.3482348e-19]
 [4.4438050e-08 9.9961567e-01 2.2583772e-06 8.7315346e-12 3.5157619e-04
  3.9966375e-07 6.6495458e-09 1.2847998e-09 3.0034174e-05 1.1393707e-09]
 [9.9999976e-01 4.0636605e-15 5.0467208e-10 1.2298606e-12 9.1732720e-13
  2.2040465e-10 4.8952407e-09 8.4342738e-10 1.0308876e-11 1.8442857e-07]]


In [16]:
print(numpy.argmax(prediction, axis=1))
print(Y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
